apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.16.1
      chart: cert-manager
      helm:
        releaseName: cert-manager
        valueFiles: 
          - $values/apps/cert-manager/environment/dev/values-settings.yaml
    - repoURL: https://github.com/Tim-Black/argoCD-Poc.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc