apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appsets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: local-dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim-Black/argoCD-Poc.git
        targetRevision: HEAD
        path: 'nginx-chart/{{.cluster}}'
      destination:
        server: '{{.url}}'
        namespace: appsets